#服务端口
server:
  port: 8220
  # 服务名
spring:
  application:
    name: ketai‐eureka
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # 服务地址
eureka:
  instance:
    hostname: localhost
  #Eureka客户端与Eureka服务端进行通信的地址
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #是否将自己注册到Eureka服务器中，本身是服务器，无需注册
    registerWithEureka: false
    # 是否需要拉取服务信息
    fetchRegistry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
